# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'One Entry Preview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for One Entry Preview
  pod 'Alamofire'
  pod 'SDWebImageSwiftUI'

end
