import Head from 'next/head'
import Link from 'next/link'

export default function Home({pages}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon" />
      </Head>
      <header>
        <div className="container">
          <div className="menu">
            {pages.map((page, index) => (<Link key={index} href={page.pageUrl}>{page.localizeInfos.en_US.title}</Link>))}
          </div>
        </div>
      </header>
    </>
  );
}

export async function getServerSideProps({req, res}) {
  const response = await fetch(
    "/api/content/pages",
    {
      method: "get",
      headers: {
        Authorization: "Bearer <AUTH_TOKEN>",
        "Content-Type": "application/json",
      },
    }
  );
  const pages = await response.json();
  return {
    props: {
      pages,
    }
  }
}
